# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/amazon/thempis/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/amazon/thempis

PRODUCT_COPY_FILES += \
    vendor/amazon/thempis/proprietary/bin/autokd:$(TARGET_COPY_OUT_SYSTEM)/bin/autokd \
    vendor/amazon/thempis/proprietary/bin/nvram_daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/nvram_daemon \
    vendor/amazon/thempis/proprietary/etc/firmware/WIFI_RAM_CODE:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/WIFI_RAM_CODE \
    vendor/amazon/thempis/proprietary/etc/firmware/WIFI_RAM_CODE_E6:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/WIFI_RAM_CODE_E6 \
    vendor/amazon/thempis/proprietary/etc/firmware/WIFI_RAM_CODE_MT6628:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/WIFI_RAM_CODE_MT6628 \
    vendor/amazon/thempis/proprietary/etc/firmware/WIFI_RAM_CODE_MT6630:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/WIFI_RAM_CODE_MT6630 \
    vendor/amazon/thempis/proprietary/etc/firmware/WMT.cfg:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/WMT.cfg \
    vendor/amazon/thempis/proprietary/etc/firmware/atmel_mxt_1066.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/atmel_mxt_1066.fw \
    vendor/amazon/thempis/proprietary/etc/firmware/atmel_mxt_1664.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/atmel_mxt_1664.fw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis00_mxt_1066.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis00_mxt_1066.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis00_mxt_1664.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis00_mxt_1664.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis01_mxt_1066.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis01_mxt_1066.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis01_mxt_1664.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis01_mxt_1664.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis10_mxt_1066.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis10_mxt_1066.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis10_mxt_1664.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis10_mxt_1664.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis11_mxt_1066.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis11_mxt_1066.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis11_mxt_1664.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis11_mxt_1664.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis_mxt_1066.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis_mxt_1066.fw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis_mxt_1066.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis_mxt_1066.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis_mxt_1664.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis_mxt_1664.fw \
    vendor/amazon/thempis/proprietary/etc/firmware/memphis_mxt_1664.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/memphis_mxt_1664.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/mt6628_ant_m1.cfg:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mt6628_ant_m1.cfg \
    vendor/amazon/thempis/proprietary/etc/firmware/mt6628_patch_e1_hdr.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mt6628_patch_e1_hdr.bin \
    vendor/amazon/thempis/proprietary/etc/firmware/mt6628_patch_e2_0_hdr.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mt6628_patch_e2_0_hdr.bin \
    vendor/amazon/thempis/proprietary/etc/firmware/mt6628_patch_e2_1_hdr.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mt6628_patch_e2_1_hdr.bin \
    vendor/amazon/thempis/proprietary/etc/firmware/mt6630_ant_m1.cfg:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mt6630_ant_m1.cfg \
    vendor/amazon/thempis/proprietary/etc/firmware/mt6630_patch_e3_0_hdr.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mt6630_patch_e3_0_hdr.bin \
    vendor/amazon/thempis/proprietary/etc/firmware/mt6630_patch_e3_1_hdr.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mt6630_patch_e3_1_hdr.bin \
    vendor/amazon/thempis/proprietary/etc/firmware/thebes00_mxt_1664.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/thebes00_mxt_1664.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/thebes01_mxt_1664.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/thebes01_mxt_1664.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/thebes10_mxt_1664.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/thebes10_mxt_1664.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/thebes11_mxt_1664.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/thebes11_mxt_1664.raw \
    vendor/amazon/thempis/proprietary/etc/firmware/thebes_mxt_1664.raw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/thebes_mxt_1664.raw \
    vendor/amazon/thempis/proprietary/lib/hw/audio.primary.mt8135.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/audio.primary.mt8135.so \
    vendor/amazon/thempis/proprietary/lib/hw/camera.mt8135.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.mt8135.so \
    vendor/amazon/thempis/proprietary/lib/hw/hwcomposer.mt8135.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/hwcomposer.mt8135.so \
    vendor/amazon/thempis/proprietary/lib/hw/sensors.mt8135.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/sensors.mt8135.so \
    vendor/amazon/thempis/proprietary/lib/lib3a.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib3a.so \
    vendor/amazon/thempis/proprietary/lib/libJpgEncPipe.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libJpgEncPipe.so \
    vendor/amazon/thempis/proprietary/lib/libaudiocompensationfilter.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiocompensationfilter.so \
    vendor/amazon/thempis/proprietary/lib/libaudiocustparam.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiocustparam.so \
    vendor/amazon/thempis/proprietary/lib/libbluetooth_hw_test.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbluetooth_hw_test.so \
    vendor/amazon/thempis/proprietary/lib/libbluetooth_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbluetooth_mtk.so \
    vendor/amazon/thempis/proprietary/lib/libbluetooth_mtk_pure.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbluetooth_mtk_pure.so \
    vendor/amazon/thempis/proprietary/lib/libbluetooth_relayer.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbluetooth_relayer.so \
    vendor/amazon/thempis/proprietary/lib/libbluetoothem_mtk.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbluetoothem_mtk.so \
    vendor/amazon/thempis/proprietary/lib/libbt-vendor.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbt-vendor.so \
    vendor/amazon/thempis/proprietary/lib/libcam.camadapter.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam.camadapter.so \
    vendor/amazon/thempis/proprietary/lib/libcam.campipe.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam.campipe.so \
    vendor/amazon/thempis/proprietary/lib/libcam.camshot.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam.camshot.so \
    vendor/amazon/thempis/proprietary/lib/libcam.client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam.client.so \
    vendor/amazon/thempis/proprietary/lib/libcam.device1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam.device1.so \
    vendor/amazon/thempis/proprietary/lib/libcam.exif.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam.exif.so \
    vendor/amazon/thempis/proprietary/lib/libcam.paramsmgr.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam.paramsmgr.so \
    vendor/amazon/thempis/proprietary/lib/libcam.utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam.utils.so \
    vendor/amazon/thempis/proprietary/lib/libcam_mmp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam_mmp.so \
    vendor/amazon/thempis/proprietary/lib/libcam_platform.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam_platform.so \
    vendor/amazon/thempis/proprietary/lib/libcam_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcam_utils.so \
    vendor/amazon/thempis/proprietary/lib/libcamalgo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcamalgo.so \
    vendor/amazon/thempis/proprietary/lib/libcamdrv.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcamdrv.so \
    vendor/amazon/thempis/proprietary/lib/libcameraanalyzer.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcameraanalyzer.so \
    vendor/amazon/thempis/proprietary/lib/libcameracustom.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcameracustom.so \
    vendor/amazon/thempis/proprietary/lib/libcustom_nvram.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcustom_nvram.so \
    vendor/amazon/thempis/proprietary/lib/libfeatureio.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfeatureio.so \
    vendor/amazon/thempis/proprietary/lib/libfile_op.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfile_op.so \
    vendor/amazon/thempis/proprietary/lib/libimageio.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libimageio.so \
    vendor/amazon/thempis/proprietary/lib/libinvensense_hal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libinvensense_hal.so \
    vendor/amazon/thempis/proprietary/lib/libmatv_cust.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmatv_cust.so \
    vendor/amazon/thempis/proprietary/lib/libmmprofile.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmprofile.so \
    vendor/amazon/thempis/proprietary/lib/libmotion.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmotion.so \
    vendor/amazon/thempis/proprietary/lib/libmpo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmpo.so \
    vendor/amazon/thempis/proprietary/lib/libmpoencoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmpoencoder.so \
    vendor/amazon/thempis/proprietary/lib/libnvram_daemon_callback.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnvram_daemon_callback.so \
    vendor/amazon/thempis/proprietary/lib/libnvram_platform.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnvram_platform.so \
    vendor/amazon/thempis/proprietary/lib/libnvram_sec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnvram_sec.so \
    vendor/amazon/thempis/proprietary/lib/libnvramagentclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libnvramagentclient.so \
    vendor/amazon/thempis/proprietary/lib/libsmartvolume.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsmartvolume.so \
    vendor/amazon/thempis/proprietary/vendor/etc/dolby/ds1-0020.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/ds1-0020.xml \
    vendor/amazon/thempis/proprietary/vendor/etc/dolby/ds1-0021.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/ds1-0021.xml \
    vendor/amazon/thempis/proprietary/vendor/firmware/inv_dmpfirmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/inv_dmpfirmware.bin \
    vendor/amazon/thempis/proprietary/vendor/firmware/maxtouch.20.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/maxtouch.20.cfg \
    vendor/amazon/thempis/proprietary/vendor/firmware/maxtouch.20.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/maxtouch.20.fw
